### ISSUE TITLE
Cannot redirect to GetStudent after successful update

### ISSUE THREAD

**Issue by merajmasuk** [merajmasuk/student-information-management-webdev#6]
#### Description

After filling up update form and hitting enter, the page redirects to /update/<id> instead of /std_detail/<id>. This leads to a rendering error due an exception related to NoReverseMatch.

#### Traceback

```
Environment:


Request Method: POST
Request URL: http://localhost:8000/update/1

Django Version: 4.1.1
Python Version: 3.10.6
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'day1']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']



Traceback (most recent call last):
  File "/home/meraj/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/meraj/.local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/meraj/Repos/student-information-management-webdev/djangolessons/djangoproject/day1/views.py", line 54, in UpdateStudent
    return redirect(reverse('.views.GetStudent', kwargs=dict(student)))
  File "/home/meraj/.local/lib/python3.10/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/home/meraj/.local/lib/python3.10/site-packages/django/urls/resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)

Exception Type: NoReverseMatch at /update/1
Exception Value: Reverse for '.views.GetStudent' not found. '.views.GetStudent' is not a valid view function or pattern name.
```

**Comment by merajmasuk** [comment]
The code is in this PR #4
